### PR TITLE
Added cmd-E shortcut (search for the selected text)

### PR DESCRIPTION
**Pull request by laughedelic**
I'm using this more often than cmd-F. 

If you want to search for a word that you see in the text, (once selected) instead of cmd-C, cmd-F, cmd-V, you can just do cmd-E. And then use cmd-G and cmd-shift-G.

### CODE REVIEW

**Comment by jlevy** [comment]
Interesting. Agree this one is super useful — when it works. Any idea if it's just an informal convention in many apps vs a standard one? It's not listed at https://support.apple.com/en-us/HT201236

**Comment by jlevy** [comment]
Inclined to list it regardless, just wondering if we should put a "(in many apps)" note or similar since I think it's less universal than cmd-F?

**Comment by laughedelic** [comment]
@jlevy yep, it's strange that it's not listed there. But who knows, it doesn't mean anything, probably they just forgot it. It's not declared as a complete list of "official" shortcuts. Plus it says

> To learn more shortcuts, check the menus of the app you're using.

In my experience cmd-E works in any browser, pdf-viewer and any text editor, i.e. basically any app where you can read text and select it.

**Comment by jlevy** [comment]
:+1: All righty then. Thanks for the addition!

**Pull request merged**
